# Generated by Django 3.1.6 on 2021-02-18 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='カテゴリー')),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('summery', models.CharField(max_length=255, verbose_name='記事の要約')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_date', models.DateTimeField(verbose_name='作成日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.articlecategory')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
