# Generated by Django 3.1.7 on 2021-02-28 21:54

import django.contrib.auth.validators
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(verbose_name='投稿日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='no_name', help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='name'),
        ),
    ]
