# Generated by Django 3.1.7 on 2021-03-15 00:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_auto_20210313_0952"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="タグの名前")),
            ],
            options={
                "db_table": "articles_tags",
            },
        ),
    ]
