# Generated by Django 3.1.7 on 2021-03-15 01:06

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tag",
            field=models.ManyToManyField(to="article.Tag", verbose_name="タグ"),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="article.articlecategory",
                verbose_name="カテゴリ",
            ),
        ),
    ]
